config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: {minimum:6, maximum:100}
    validates :description, presence: true, length: {minimum:10, maximum:300}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]

    def show
    end 

    def index
        @articles = Article.all 
    end 

    def new
        @article = Article.new
    end 

    def edit
    end 

    def create
        @article = Article.new(article_params)
        if @article.save 
            flash[:notice] = "Article was successfully added"
        # redirect_to article_path(@article)
            redirect_to @article
        else
            render 'new'
        end
    end

    def update
        
        if @article.update(article_params)
           flash[:notice] = "Article was updated successfully"
            redirect_to @article
        else
            render 'edit'
        end 
        
    end 

    def destroy
        @article.destroy
        redirect_to articles_path
    end

    private
    def set_article
        @article = Article.find(params[:id])
    end
    
    def article_params
        params.require(:article).permit(:title, :description)
    end
end

    

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end

   def about
   end 
   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h2> check the following errors</h2>
  <ul>
  <%= @article.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>

<%= form_with(model: @article, local: true) do |f| %>

<p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
</p>

<p>
    <%= f.label :description %><br/>
    <%= f.text_area :description%>
</p>

<p>
    <%= f.submit %>
</p>

<% end %>

app/views/articles/edit.html.erb
<%= render 'form' %>

<td><%= link_to 'Cancel', articles_path %></td>

app/views/articles/index.html.erb
<h1>Articles List</h1>

<table>
   <thead>
      <tr>
         <th>Title</th>
         <th>Description</th>
         <th>Actions</th>
    </tr>
   </thead>

   <tbody>
     <% @articles.each do |c| %>
   <tr>
      <td><%= c.title %></td>
      <td><%= c.description %></td>
      <td><%= link_to 'Create', new_article_path(c) %></td>
      <td><%= link_to 'Edit', edit_article_path(c) %></td>
       <td><%= link_to 'Show', article_path(c) %></td>
      <td><%= link_to 'Delete', article_path(c), method: :delete, data: { confirm: 'Are you sure Smasem?' } %></td>
    </tr>
    <% end %>
   </tbody>



#article in line 17 is an object of the article I'm iterating on 
#and I can write it with this way and ruby is smart enough to know which
# Id i'm reflecting on or I can put it as (article.id)

app/views/articles/new.html.erb
<%= render 'form' %>
<td><%= link_to 'Cancel and Return to main list', articles_path %></td>

app/views/articles/show.html.erb
<h1> this is the show view</h1>

<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description: </strong><%= @article.description %></p>

<td><%= link_to 'Edit', edit_article_path(@article) %></td> |
<td><%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: 'Are you sure Smasem?' } %></td>|
<td><%= link_to 'Return to main list', articles_path %></td>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1> this is the about page</h1>


<td><%= link_to 'Articles', root_path %></td>
<td><%= link_to 'Home Page', about_path %></td>

app/views/pages/home.html.erb
<h1> This is the home page</h1>
<td><%= link_to 'Articles', articles_path %></td>
<td><%= link_to 'About Page', about_path %></td>